- type: antagSpecifier
  abstract: true
  id: BaseAntagSpecifier
  jobBlacklist:
  - CentralCommandOfficial
  - DeathSquad
  - ERTLeader
  - ERTChaplain
  - ERTEngineer
  - ERTSecurity
  - ERTMedical
  - ERTJanitor
  - CBURN
  blacklist:
    components:
    - AntagImmune

# Command
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: CommandBlacklistedAntag
  jobBlacklist:
  - CountySheriff
  - Sheriff

# Borgs
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: CyborgBlacklistedAntag
  jobBlacklist: []

# Learner Roles
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: InternBlacklistedAntag
  jobBlacklist: []

# Security
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: SecurityBlacklistedAntag
  jobBlacklist:
  - CountySheriff
  - Sheriff
  - Lawman

- type: antagSpecifier
  abstract: true
  parent: [ CommandBlacklistedAntag, SecurityBlacklistedAntag ]
  id: MindshieldRestrictedAntag

- type: antagSpecifier
  abstract: true
  parent: [ MindshieldRestrictedAntag, CyborgBlacklistedAntag, InternBlacklistedAntag ]
  id: RestrictedAntag
